twig:
<<<<<<< ours
    default_path: '%kernel.project_dir%/templates'
    paths:
        'waypoints': ~
||||||| base
    default_path: '%kernel.project_dir%/templates'
=======
    file_name_pattern: '*.twig'
>>>>>>> theirs

when@test:
    twig:
        strict_variables: true
