controllers:
<<<<<<< ours
    resource: ../src/Controller/
    type: attribute
||||||| base
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
=======
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
>>>>>>> theirs
